### ISSUE TITLE
serial.vcxproj: AdditionalIncludeDirectories relative for solution not project

### ISSUE THREAD

**Issue by ramirahikkala** [wjwwood/serial#105]
If I add serial.vcxproj to my solution header files cannot be found. AdditionalIncludeDirectories should be relative for project to make it possible to add project to other solutions too.

It is now like this:
$(SolutionDir)..\include;%(AdditionalIncludeDirectories)
Should be:
$(ProjectDir)..\\..\include;%(AdditionalIncludeDirectories)

**Comment by wjwwood** [comment]
Thanks for pointing that out! Can you open a pull request to that effect? That way it will attributed to you and our CI can automatically test it.
