### ISSUE TITLE
Makefile missing uninstall target

### ISSUE THREAD

**Issue by artifactz** [wjwwood/serial#107]
The [README.md](https://github.com/wjwwood/serial/blob/master/README.md) mentions a `make uninstall` target. But there is none.
The main [Makefile](https://github.com/wjwwood/serial/blob/master/Makefile) redirects the uninstall target to build/Makefile, which does not contain it.

**Comment by chuong98** [comment]
Any update to @artifactz comment. I can not uninstall with  `make uninstall` in the newest version..
