### ISSUE TITLE
Strange data coming from serial port

### ISSUE THREAD

**Issue by karimcitoh** [wjwwood/serial#117]
Sorry I am a bit new into serial communication data.

I am running the example provided and the I am getting only weird characters, but I am sure the baud rate I am using is correct. Is there any way to decode it?

Thanks in advance,

<img width="522" alt="screen shot 2015-11-25 at 19 35 10" src="https://cloud.githubusercontent.com/assets/8901428/11406042/d49a95f2-93ab-11e5-96a9-2ecb4dc84bb6.png">

**Comment by wjwwood** [comment]
What do you have connected to the serial port? Also please do not post a screen shot, instead copy and paste the text into the issue.

**Comment by karimcitoh** [comment]
My excuses for the wrong issue, and also for copying the screenshot. It was my fault, I was not using correct settings in the device I was connecting to!

But thanks for the help and the quick answer.
