### ISSUE TITLE
Cannot write data

### ISSUE THREAD

**Issue by Obbart** [wjwwood/serial#121]
Hi, I'm trying to send data between two VSPs created with:
socat -d -d pty,raw,echo=0 pty,raw,echo=0
Opening one port in my program using your library and the other port in putty I cannot send data from program to putty but only read strings from putty.
write always returns zero

**Comment by wjwwood** [comment]
I've not used `socat` before. I'd recommend trying your setup with two instances of pyserial or miniterm or something that is "known" to work.

**Comment by Obbart** [comment]
I've just tried the communication between two instances of putty and it works just fine in both directions.
It's non mandatory using socat, if you know another method to create a pair of virtual serial ports let me know, i'm just trying to simulate a connection between my software and a robot controller that in this case is a "simulator" running on this pc.
thaks :)

**Comment by Obbart** [comment]
in file unix.cc, line 551-557 

while (bytes_read < size) {
    int64_t timeout_remaining_ms = total_timeout.remaining();
    if (timeout_remaining_ms <= 0) {
      // Timed out
      break;
    }
...
}
timeout_remaining_ms is always a negative number so the function deos not write to the port

**Comment by wjwwood** [comment]
Make sure you've set the read timeout: https://github.com/wjwwood/serial/blob/1.2.1/include/serial/serial.h#L424-L459

**Comment by wjwwood** [comment]
I'm gonna close this. Comment if new information comes up.

**Comment by airduke** [comment]
I had a similar issue. Problem was actually on the other end of the Serial line not reading properly and the pselect timing out is the symptom I saw from this end.
If you are in a similar spot, try putting a loopback on the other end of the serial as described in the preamble of serial_example.cc to quickly test if you have a similar issue.
