### ISSUE TITLE
error:serial.lib is not a valid win32 application

### ISSUE THREAD

**Issue by xxzl0130** [wjwwood/serial#124]
I downloaded the zip and tried the test_serial but visual studio came to an error that serial.lib is not a valid win32 application.
![image](https://cloud.githubusercontent.com/assets/9150038/12670739/bc366d88-c6a5-11e5-9542-f45f06513418.png)

How to fix it?
BTW, I'm using Visual Studio 2015 on Windows 10.
Thanks.

**Comment by xxzl0130** [comment]
I solved this problem by setting a new project.
It seems that this error comes from AdditionalDependencies.
Hope solving this problem.

**Comment by wjwwood** [comment]
You have to select the correct project in Visual Studio. You cannot "run" the library, which is what is happening here. You need to run the example or write your own program which uses the library.
