### ISSUE TITLE
Compile as DLL For Consumption by C#

### ISSUE THREAD

**Issue by davidbitton** [wjwwood/serial#138]
I would like to consume this library from C#, however C# requires a DLL. I tried to change the Configuration Type to DLL, but VS2k15 fails with this error when I click OK.

![error](https://www.evernote.com/l/AAqYK8szYQ9FEKuRHRh-BXzmqaPLADOGUjsB/image.png)

Have you tried to create a managed C++ wrapper for this by any chance? Thanks!

**Comment by vasek-cz** [comment]
What is the reason you need to create a C++ wrapper around this library? Did you consider using SerialPort C# class?

**Comment by davidbitton** [comment]
i do not remember.
