### ISSUE TITLE
Compiler warning in win.cc '_prefix_port_if_needed': not all control paths return a value'

### ISSUE THREAD

**Issue by smkanadl** [wjwwood/serial#149]
When compiling for Windows, I get a compiler warning, complaining about a missing return value in _prefix_port_if_needed for the else case. Is this is a bug? Shouldn't be input returned in the 'else' case?

**Comment by wjwwood** [comment]
Are you talking about this function?

https://github.com/wjwwood/serial/blob/c16faab6ea7e60645eb9a2e3f7443ea18e55e86c/src/impl/win.cc#L23-L32

There is no `else` case there...

**Comment by smkanadl** [comment]
You are absolutely right. It was not fixed in the last official release 1.2.1 and I haven't looked into the master. Please excuse my negligence.
