### ISSUE TITLE
Undefined Refernce

### ISSUE THREAD

**Issue by helloguys1913** [wjwwood/serial#162]

**Comment by helloguys1913** [comment]
$ make
[  9%] Automatic moc for target my_project
[  9%] Built target my_project_automoc
[ 18%] Automatic moc for target serial
[ 18%] Built target serial_automoc
[ 63%] Built target serial
[ 72%] Linking CXX executable my_project.exe
CMakeFiles/my_project.dir/examples/dialog.cpp.o:dialog.cpp:(.text+0x790): undefined reference to `serial::list_ports()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/my_project.dir/build.make:151: my_project.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:69: CMakeFiles/my_project.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by sirop** [comment]
This is rather a Qt question.

**Comment by wjwwood** [comment]
This usually is because you're not linking against the serial library.

I'm going to close this because I believe the issue has been addressed. Feel free to continue to comment and I can reopen if necessary.
