### ISSUE TITLE
Unable to set Baudrate

### ISSUE THREAD

**Issue by Matthias199** [wjwwood/serial#166]
Hello,

I want to develop for my RF Modules a serial driver,
but I have problems with setting higher baud rates.

' my_serial.setPort(Port);
my_serial.setBaudrate(500000);
my_serial.setTimeout(2000,2000,2000,2000,2000);
my_serial.open();
'

is not working the output from stty is
'stty -F /dev/ttyUSB0
speed 9600 baud; line = 0;
min = 0; time = 0;
-brkint -icrnl -imaxbel
-opost
'
but after setting the port up with putty

'stty -F /dev/ttyUSB0
speed 500000 baud; line = 0;
min = 1; time = 0;
-brkint -icrnl ixoff -imaxbel
-opost -onlcr
-isig -icanon -iexten -echo -echoe -echok
'

And if I try to start my driver he is working perfectly so it stems that setBaud is not able to set this rate but why?

putty is giving me the debug output from the module and the driver I have written also, after setting the port up with putty, so why is setBaudrate not able to set my wish baud rate ?

Serial lib is from ros-jade

I am using Linux Ubuntu 14.04

MFG

Matthias

**Comment by wjwwood** [comment]
Without the hardware in front of me, it's hard to say what might be happening. If you find more information feel free to add it to this issue, but for now I'll close it. If you find something I can act on, I'll reopen it.

Thanks!
