### ISSUE TITLE
How to Asynchronous serial reading and writing?

### ISSUE THREAD

**Issue by DavidHan008** [wjwwood/serial#168]
How to Asynchronous serial reading and writing?

**Comment by luciancaetano** [comment]
The serial port is handled as a file system file so you can use the same strategy as the libuv file system handles, file system operations are performed on a thread pool, when done return the result in an event queue , which soon notifies you about reading the data.

**Comment by wjwwood** [comment]
There is no asynchronous api for reading or writing serial ports in this library. If you need that, you need some system that has a run-loop or some other asynchronous mechanism, I recommend asio: https://think-async.com/
