### ISSUE TITLE
Opening multiple serial ports

### ISSUE THREAD

**Issue by rupak-d** [wjwwood/serial#183]
I want to use 3 TI mmWave radar's simultaneously on an Ubuntu system using ROS. Everytime I launch the second radar, the first one dies giving this message-

[ INFO] [1533763639.507378042]: mmWaveCommSrv: Sending command to sensor: 'sensorStop'
[ INFO] [1533763639.573949686]: mmWaveCommSrv: Received response from sensor: 'sensorStop
Done
mmwDemo:/>'

Is the sensorStop command something this serial package is giving?

**Comment by wjwwood** [comment]
No, this package doesn't depend on ROS, so any ROS node related stuff is specific to something other than this library. This library only opens/closes serial ports and sends arbitrary data to/from it with read/write. It has no support for specific devices or command sets.
