### ISSUE TITLE
How do I compile and run serial_example in Ubuntu?

### ISSUE THREAD

**Issue by tomsasson** [wjwwood/serial#191]
So far I've been using Visual Studio 2017 to compile and run my version of test_serial project (with serial_example.cc).
I would like to do the same on linux, so is there a Makefile or CMakeLists.txt file to compile and run an executable?

**Comment by cubimon** [comment]
> g++ serial_example.cc -lserial -L ../build/devel/lib -I../include -o test_serial
> LD_LIBRARY_PATH=`pwd`/../build/devel/lib ./test_serial
