### ISSUE TITLE
rs485 support

### ISSUE THREAD

**Issue by nicola-lunghi** [wjwwood/serial#196]
Hi
any possibility of RS485 support in the future?

https://github.com/cbrake/linux-serial-test/blob/aed2a6e78160b63295368d70dbdbc19fe3a38225/linux-serial-test.c#L460

Thanks
Nick

**Comment by romainreignier** [comment]
Indeed it would be nice.
Maybe you can propose a pull request to help to add this feature.

**Comment by bryanibit** [comment]
rs485 is  not supported now?

**Comment by bryanibit** [comment]
I use 'apt-get install ros-kinetic-serial' to install the package. I find it supports rs485!

**Comment by wjwwood** [comment]
Confirmation on whether or not this is working and/or a pull request to enable this would be good. Closing for now though.
