### ISSUE TITLE
SerialNumber read interface if available

### ISSUE THREAD

**Issue by rahuldeo2047** [wjwwood/serial#201]
In case the serial is attached to the system and if a device which can provide vendor or product information; a method will allow users to enumerate all the serials and select the specified serial connection which has the given vendor and product ID associated.
Information can be availed as follows:

VendorID
ProductID
DeviceID
iSerialNumber

**Comment by rahuldeo2047** [comment]
OK found usb_sysfs_friendly_name

will check it first.

**Comment by wjwwood** [comment]
Might be useful if it can be made to be portable. Closing for now, feel free to comment and I can reopen if needed.

**Comment by rahuldeo2047** [comment]
I will get back to check. Unable to recall currently. Will check usb_sysfs_friendly_name as well. Aimed to select one serial interface when multiple same vid and pid connected and aimed to see if rest of the two did or serial number differed. And remained identifiable everytime. Thanks for the library.
