### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by pktiuk** [wjwwood/serial#206]
I have downloaded repository, compiled using `catkin_make` , and connected a cheap USB-UART module to check how it works.
when i used command: 
`$ rosrun serial serial_example -e|/dev/ttyUSB0 9600 TestString`
i got:
`bash: /dev/ttyUSB0: Permission denied`
I belong to dialout group, and don't know what else I can do.

(The same problem appears when i try to check this library on RaspberryPi with ROS.)

**Comment by CrazyPopLin** [comment]
check here: https://websistent.com/fix-serial-port-permission-denied-errors-linux/

**Comment by wjwwood** [comment]
I'm going to close this because it is old, but please comment and I can reopen if needed.
