### ISSUE TITLE
"undefined reference to" problems

### ISSUE THREAD

**Issue by AndyRay1998** [wjwwood/serial#219]
When I am using it in ROS-kinetic and try to catkin_make using g++, the problems show like in the picture.
![图片](https://user-images.githubusercontent.com/35843385/78144163-d4428380-7461-11ea-960d-11de0bcc6b7c.png)
Do anyone know what is going on here?
I am using ubuntu 16.04 64bit.

**Comment by wjwwood** [comment]
I know this is an old issue, but for people arriving here from the future:

Seems like you're not linking to the serial library, so missing a `target_link_libraries` or something similar.

In the future, try not to include pictures of text, and perhaps provide the CMakeLists.txt.
