### ISSUE TITLE
Noetic Release

### ISSUE THREAD

**Issue by tonybaltovski** [wjwwood/serial#222]
Could you please do a release for Noetic?

**Comment by doisyg** [comment]
Yes, that would be nice as many drivers rely on this

**Comment by gmsanchez** [comment]
Yes, please

**Comment by Juba19** [comment]
Agree, I hope soon ! It will be a helpful tool for NOETIC. Thank you

**Comment by droemer7** [comment]
Seconding this as well, but I suppose it can be built from source and should work?

**Comment by doisyg** [comment]
> Seconding this as well, but I suppose it can be built from source and should work?

Yes, working for me from src

**Comment by Tobias-Fischer** [comment]
Ping @wjwwood 
Working for me fine from src, too.

**Comment by joshnewans** [comment]
It would be great to have this available as a noetic release. It is working fine from source for me, but it is a dependency for my package which I would like to be able to distribute for noetic.

**Comment by stwirth** [comment]
@wjwwood ping

**Comment by julianraheema** [comment]
Any time soon for this package to be in distribute for noetic as ros package?

**Comment by HappySamuel** [comment]
@Tobias-Fischer 

How do you get it work on Noetic with src? I managed to catkin_make successfully with the src, but when i run the program, it crashed. 

![Screenshot from 2021-02-15 14-27-27](https://user-images.githubusercontent.com/18137963/107912713-fcfc3a80-6f99-11eb-9320-a6f7c44f24bc.png)

Best,
Samuel

**Comment by Tobias-Fischer** [comment]
Hi @HappySamuel - it's impossible to tell from the screenshot. As the error message says, the serial port is already open. This seems more like a bug in the downstream code? I didn't need to modify anything in the code that I am using (um7).

**Comment by lauralindzey** [comment]
@wjwwood bump =)

**Comment by Tobias-Fischer** [comment]
Ping @wjwwood

**Comment by HappySamuel** [comment]
Hi @Tobias-Fischer 

I found the root cause of that issue. It's because of my another package that caused the problem, they interfere each other if they're catkin_make under same workspace. If separated them into different workspace, and linked together, this issue will not persist. Previously on Ubuntu 16.04 and 18.04, i didn't face this issue, it's because i installed the serial package using sudo apt-get install, hence it's in different workspace (/opt/ros/version/...). Due to yet to have distribute version of serial package in ros noetic, this is the solution i applied.

Hope, there'll soon release noetic version of serial package. @wjwwood 

Best,
Samuel

**Comment by HappySamuel** [comment]
Still waiting for noetic release...

**Comment by SubaruArai** [comment]
If there is nobody doing it, I can make a pr to ros/rosdistro. @wjwwood can I make a pr to rosdistro/noetic?

**Comment by SubaruArai** [comment]
@wjwwood I've made a draft, please approve if you feel ok.
https://github.com/ros/rosdistro/pull/31385

**Comment by SubaruArai** [comment]
@wjwwood I made a draft pr. If you think it's fine, please accept.
https://github.com/ros/rosdistro/pull/31386

**Comment by wjwwood** [comment]
I had to close it, I don't think you used bloom to release the repository, which is required. I was wanting to switch to pure CMake, away from catkin, and to do that I needed to fix CI with GitHub Actions, and so on and so forth. I haven't had time to do that, so I'll just release it as-is.

**Comment by wjwwood** [comment]
https://github.com/ros/rosdistro/pull/31420 this will get merged soon prob

**Comment by SubaruArai** [comment]
@wjwwood My bad, thank you!
