### ISSUE TITLE
Any update for ROS noetic and  ubuntu 20.04?

### ISSUE THREAD

**Issue by Coderx7** [wjwwood/serial#253]
Hi, is there any plan to release package for ubuntu 20.04, like what we have for melodic and ubuntu 18.04? 
Thanks a lot in advance

**Comment by tkazik** [comment]
Duplicate of https://github.com/wjwwood/serial/issues/222 ...but long time no response there.

**Comment by HappySamuel** [comment]
Hi @Coderx7 

Now you can install serial using deb package.
`$ sudo apt install ros-noetic-serial`

Best,
Samuel

**Comment by Coderx7** [comment]
@HappySamuel Thanks a lot for the update samuel really appreciate it
