### ISSUE TITLE
Installing on windows

### ISSUE THREAD

**Issue by Dom-Cantrill** [wjwwood/serial#268]
Are there any precompiled binaries for windows. I'm finding it very difficult to build the library on windows with the given instructions. Is there a simpler way to compile it.

**Comment by wjwwood** [comment]
> Are there any precompiled binaries for windows.

No, unfortunately not.

> I'm finding it very difficult to build the library on windows with the given instructions. Is there a simpler way to compile it.

Sorry, there is not. There is a VS project here: https://github.com/wjwwood/serial/tree/main/visual_studio but I don't know if it is still working.
