### ISSUE TITLE
Does it make sense to close the Serial object upon destruction ?

### ISSUE THREAD

**Issue by Hish15** [wjwwood/serial#273]
https://github.com/wjwwood/serial/blob/69e0372cf0d3796e84ce9a09aff1d74496f68720/src/serial.cc#L77

The current behavior is to delete an underlaying pointer, this does the job, but can lead to an exception on some cases.

**Comment by Hish15** [comment]
I realized that `delete pimpl_` does call   `pimpl_` destructor which calls  `pimpl_::close`.

**Comment by sudotamm** [comment]
It will crash if throw exception not been catched when `delete pimpl_`, how do you avoid this? @Hish15

**Comment by Hish15** [comment]
Hello @sudotamm, I'm an user of this not a maintainer. 
What you say is right, the `delete pimpl_` calls `pimpl_::close` which is not noexcept...
You might want to open an issue/discussion
