### ISSUE TITLE
Documentation request: exception list

### ISSUE THREAD

**Issue by trainman419** [wjwwood/serial#87]
As a user trying to write robust code using the serial library, it would be useful to know which exceptions might be thrown from each function, so that I can catch them and handle each error appropriately.

**Comment by wjwwood** [comment]
Most of the functions were documented, a few were not explicitly stating that they threw, but the common variation did (e.g. `read` and `write`), and a few had old references to an exception that was replaced with a standard library exception, but I fixed everything I could find in 52197af.

I won't guarantee that this is exhaustive, but I've reviewed this in the past and just now. Many of the functions have had this documented for a while, for example:

- `Serial::open`: http://wjwwood.io/serial/doc/1.1.0/classserial_1_1_serial.html#af3644ed1a9d899b70e9d63bb9b808d62
- `Serial::waitForChange`: http://wjwwood.io/serial/doc/1.1.0/classserial_1_1_serial.html#a419dc984258956a5adb41fb8c86f5449

But for sure if you find anything that isn't documented please let me know.

I'll generate updated documentation for the new version I'm about to release.
